/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_WIRINGPI_H
#define PHP_WIRINGPI_H

extern zend_module_entry wiringpi_module_entry;
#define phpext_wiringpi_ptr &wiringpi_module_entry

#ifdef PHP_WIN32
# define PHP_WIRINGPI_API __declspec(dllexport)
#else
# define PHP_WIRINGPI_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(wiringpi);
PHP_MSHUTDOWN_FUNCTION(wiringpi);
PHP_RINIT_FUNCTION(wiringpi);
PHP_RSHUTDOWN_FUNCTION(wiringpi);
PHP_MINFO_FUNCTION(wiringpi);

ZEND_NAMED_FUNCTION(_wrap_wiringPiFailure);
ZEND_NAMED_FUNCTION(_wrap_wiringPiFindNode);
ZEND_NAMED_FUNCTION(_wrap_wiringPiNewNode);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSetup);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSetupSys);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSetupGpio);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSetupPhys);
ZEND_NAMED_FUNCTION(_wrap_pinModeAlt);
ZEND_NAMED_FUNCTION(_wrap_pinMode);
ZEND_NAMED_FUNCTION(_wrap_pullUpDnControl);
ZEND_NAMED_FUNCTION(_wrap_digitalRead);
ZEND_NAMED_FUNCTION(_wrap_digitalWrite);
ZEND_NAMED_FUNCTION(_wrap_pwmWrite);
ZEND_NAMED_FUNCTION(_wrap_analogRead);
ZEND_NAMED_FUNCTION(_wrap_analogWrite);
ZEND_NAMED_FUNCTION(_wrap_piBoardRev);
ZEND_NAMED_FUNCTION(_wrap_piBoardId);
ZEND_NAMED_FUNCTION(_wrap_wpiPinToGpio);
ZEND_NAMED_FUNCTION(_wrap_physPinToGpio);
ZEND_NAMED_FUNCTION(_wrap_setPadDrive);
ZEND_NAMED_FUNCTION(_wrap_getAlt);
ZEND_NAMED_FUNCTION(_wrap_pwmToneWrite);
ZEND_NAMED_FUNCTION(_wrap_digitalWriteByte);
ZEND_NAMED_FUNCTION(_wrap_digitalReadByte);
ZEND_NAMED_FUNCTION(_wrap_pwmSetMode);
ZEND_NAMED_FUNCTION(_wrap_pwmSetRange);
ZEND_NAMED_FUNCTION(_wrap_pwmSetClock);
ZEND_NAMED_FUNCTION(_wrap_gpioClockSet);
ZEND_NAMED_FUNCTION(_wrap_waitForInterrupt);
ZEND_NAMED_FUNCTION(_wrap_piThreadCreate);
ZEND_NAMED_FUNCTION(_wrap_piLock);
ZEND_NAMED_FUNCTION(_wrap_piUnlock);
ZEND_NAMED_FUNCTION(_wrap_piHiPri);
ZEND_NAMED_FUNCTION(_wrap_delay);
ZEND_NAMED_FUNCTION(_wrap_delayMicroseconds);
ZEND_NAMED_FUNCTION(_wrap_millis);
ZEND_NAMED_FUNCTION(_wrap_micros);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CRead);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CReadReg8);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CReadReg16);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CWrite);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CWriteReg8);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CWriteReg16);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CSetupInterface);
ZEND_NAMED_FUNCTION(_wrap_wiringPiI2CSetup);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSPIGetFd);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSPIDataRW);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSPISetupMode);
ZEND_NAMED_FUNCTION(_wrap_wiringPiSPISetup);
ZEND_NAMED_FUNCTION(_wrap_serialOpen);
ZEND_NAMED_FUNCTION(_wrap_serialClose);
ZEND_NAMED_FUNCTION(_wrap_serialFlush);
ZEND_NAMED_FUNCTION(_wrap_serialPutchar);
ZEND_NAMED_FUNCTION(_wrap_serialPuts);
ZEND_NAMED_FUNCTION(_wrap_serialPrintf);
ZEND_NAMED_FUNCTION(_wrap_serialDataAvail);
ZEND_NAMED_FUNCTION(_wrap_serialGetchar);
ZEND_NAMED_FUNCTION(_wrap_shiftIn);
ZEND_NAMED_FUNCTION(_wrap_shiftOut);
ZEND_NAMED_FUNCTION(_wrap_drcSetupSerial);
ZEND_NAMED_FUNCTION(_wrap_ads1115Setup);
ZEND_NAMED_FUNCTION(_wrap_max31855Setup);
ZEND_NAMED_FUNCTION(_wrap_max5322Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp23008Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp23016Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp23017Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp23s08Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp23s17Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp3002Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp3004Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp3422Setup);
ZEND_NAMED_FUNCTION(_wrap_mcp4802Setup);
ZEND_NAMED_FUNCTION(_wrap_pcf8574Setup);
ZEND_NAMED_FUNCTION(_wrap_pcf8591Setup);
ZEND_NAMED_FUNCTION(_wrap_sn3218Setup);
ZEND_NAMED_FUNCTION(_wrap_softPwmCreate);
ZEND_NAMED_FUNCTION(_wrap_softPwmWrite);
ZEND_NAMED_FUNCTION(_wrap_softPwmStop);
ZEND_NAMED_FUNCTION(_wrap_softServoWrite);
ZEND_NAMED_FUNCTION(_wrap_softServoSetup);
ZEND_NAMED_FUNCTION(_wrap_softToneCreate);
ZEND_NAMED_FUNCTION(_wrap_softToneStop);
ZEND_NAMED_FUNCTION(_wrap_softToneWrite);
ZEND_NAMED_FUNCTION(_wrap_sr595Setup);
ZEND_NAMED_FUNCTION(_wrap_ds1302rtcRead);
ZEND_NAMED_FUNCTION(_wrap_ds1302rtcWrite);
ZEND_NAMED_FUNCTION(_wrap_ds1302ramRead);
ZEND_NAMED_FUNCTION(_wrap_ds1302ramWrite);
ZEND_NAMED_FUNCTION(_wrap_ds1302clockRead);
ZEND_NAMED_FUNCTION(_wrap_ds1302clockWrite);
ZEND_NAMED_FUNCTION(_wrap_ds1302trickleCharge);
ZEND_NAMED_FUNCTION(_wrap_ds1302setup);
ZEND_NAMED_FUNCTION(_wrap_gertboardAnalogWrite);
ZEND_NAMED_FUNCTION(_wrap_gertboardAnalogRead);
ZEND_NAMED_FUNCTION(_wrap_gertboardSPISetup);
ZEND_NAMED_FUNCTION(_wrap_gertboardAnalogSetup);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64setOrigin);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64setOrientation);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64orientCoordinates);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64getScreenSize);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64point);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64line);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64lineTo);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64rectangle);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64circle);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64ellipse);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64putchar);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64puts);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64update);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64clear);
ZEND_NAMED_FUNCTION(_wrap_lcd128x64setup);
ZEND_NAMED_FUNCTION(_wrap_lcdHome);
ZEND_NAMED_FUNCTION(_wrap_lcdClear);
ZEND_NAMED_FUNCTION(_wrap_lcdDisplay);
ZEND_NAMED_FUNCTION(_wrap_lcdCursor);
ZEND_NAMED_FUNCTION(_wrap_lcdCursorBlink);
ZEND_NAMED_FUNCTION(_wrap_lcdSendCommand);
ZEND_NAMED_FUNCTION(_wrap_lcdPosition);
ZEND_NAMED_FUNCTION(_wrap_lcdCharDef);
ZEND_NAMED_FUNCTION(_wrap_lcdPutchar);
ZEND_NAMED_FUNCTION(_wrap_lcdPuts);
ZEND_NAMED_FUNCTION(_wrap_lcdPrintf);
ZEND_NAMED_FUNCTION(_wrap_lcdInit);
ZEND_NAMED_FUNCTION(_wrap_maxDetectRead);
ZEND_NAMED_FUNCTION(_wrap_readRHT03);
ZEND_NAMED_FUNCTION(_wrap_piGlow1);
ZEND_NAMED_FUNCTION(_wrap_piGlowLeg);
ZEND_NAMED_FUNCTION(_wrap_piGlowRing);
ZEND_NAMED_FUNCTION(_wrap_piGlowSetup);
ZEND_NAMED_FUNCTION(_wrap_setupNesJoystick);
ZEND_NAMED_FUNCTION(_wrap_readNesJoystick);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatPoint);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatLine);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatLineTo);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatRectangle);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatUpdate);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatClear);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatPutchar);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatPuts);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatPrintf);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatPrintSpeed);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatIntensity);
ZEND_NAMED_FUNCTION(_wrap_scrollPhatSetup);
#endif /* PHP_WIRINGPI_H */
